import {Capacitor} from '@capacitor/core';
import {CapacitorBarcodeScanner} from '@capacitor/barcode-scanner';
import {api,fieldApi,signIn,signOut,isConfigured} from '../web/backend.js';
import {readFleetQr,defaultMeters,meterLabels} from './fleet-qr.js';
const app=document.querySelector('#app'),logout=document.querySelector('#logout');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:2});
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date());
let db,session,draft={},queue=[],selected=null,busy=false,connected=false,needsLogin=false,editId=null,message='';
async function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open('abencoada-diesel-mobile',1);req.onupgradeneeded=()=>{req.result.createObjectStore('meta',{keyPath:'key'});req.result.createObjectStore('queue',{keyPath:'id'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function op(store,mode,fn){return new Promise((resolve,reject)=>{const tx=db.transaction(store,mode),req=fn(tx.objectStore(store));let value;req.onsuccess=()=>value=req.result;tx.oncomplete=()=>resolve(value);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
const get=async key=>(await op('meta','readonly',s=>s.get(key)))?.value;
const put=(key,value)=>op('meta','readwrite',s=>s.put({key,value}));
const key=name=>session.user.id+':'+name;
const fields=f=>f.meter_fields||defaultMeters(f.type);
function previous(f){const editing=editId?queue.find(r=>r.id===editId):null;const values={km:Number(f.last_km||0),engine:Number(f.last_engine||0),elevator:Number(f.last_elevator||0)};for(const r of queue)if(r.fleet===f.id&&r.id!==editId&&!r.error&&(!editing||r.createdAt<editing.createdAt))for(const k of Object.keys(values))if(r[k]!==undefined)values[k]=Math.max(values[k],r[k]);return values}
async function load(){queue=(await op('queue','readonly',s=>s.getAll())).filter(r=>r.userId===session.user.id).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));draft=await get(key('draft'))||{};selected=session.fleets.find(f=>f.id===draft.fleet&&f.active)||null}
async function saveDraft(){await put(key('draft'),draft)}
function statusHTML(){return `<p class="muted">${connected?'CONECTADO':'ÚLTIMOS DADOS SALVOS NO CELULAR'}${session.cachedAt?' · '+esc(new Date(session.cachedAt).toLocaleString('pt-BR')):''}</p>${message?`<p class="success" role="status">${esc(message)}</p>`:''}`}
function pendingHTML(){return queue.length?`<section class="card pending"><div class="row"><b>${queue.length} PENDENTE${queue.length>1?'S':''}</b><button class="secondary" id="retry" ${busy?'disabled':''}>${busy?'ENVIANDO…':'ENVIAR'}</button></div>${queue.filter(r=>r.error).map(r=>`<div class="card"><b>FROTA ${esc(r.fleet)}</b><p class="error">${esc(r.error)}</p><button class="secondary" data-correct="${r.id}">CONFERIR E CORRIGIR</button></div>`).join('')}</section>`:''}
function bindPending(){const retry=document.querySelector('#retry');if(retry)retry.onclick=sync;document.querySelectorAll('[data-correct]').forEach(b=>b.onclick=async()=>{const r=queue.find(r=>r.id===b.dataset.correct);if(!r)return;editId=r.id;draft={...r};selected=session.fleets.find(f=>f.id===r.fleet);await saveDraft();render()})}
function updatePanels(){const form=document.querySelector('#refuel');if(form&&selected){if(form.dataset.meters!==JSON.stringify(fields(selected))){render();return}const p=previous(selected);for(const k of Object.keys(meterLabels)){const label=document.querySelector('[data-previous="'+k+'"]');if(label)label.textContent=selected.record_count===0&&!queue.some(r=>r.fleet===selected.id)?'SEM REGISTRO':num(p[k]);if(form.elements[k])form.elements[k].min=p[k]}}const status=document.querySelector('#status'),pending=document.querySelector('#pending');if(status)status.innerHTML=statusHTML();if(pending){pending.innerHTML=pendingHTML();bindPending()}}
function render(){if(!session||needsLogin)return login();logout.hidden=false;app.innerHTML=`<h1>ABASTECIMENTO</h1><div class="worker">${esc(session.user.name)}</div><div id="status">${statusHTML()}</div><button class="primary" id="scan">LER QR CODE${selected?' DE OUTRA FROTA':''}</button><button class="secondary" id="manual">DIGITAR CÓDIGO DA FROTA</button><form id="fleet-code" hidden><label>CÓDIGO DA FROTA<input name="fleet" maxlength="30" autocapitalize="characters" required></label><button class="secondary" type="submit">SELECIONAR FROTA</button></form>${selected?formHTML():''}<div id="pending">${pendingHTML()}</div>`;document.querySelector('#scan').onclick=scan;document.querySelector('#manual').onclick=manual;bindPending();const form=document.querySelector('#refuel');if(form){form.oninput=()=>{draft={...draft,...Object.fromEntries(new FormData(form))};saveDraft().catch(()=>{message='Não foi possível salvar o rascunho.';updatePanels()})};form.onsubmit=submit}}
function formHTML(){const p=previous(selected),meters=fields(selected);return `<section class="card"><h2>FROTA ${esc(selected.id)}</h2><p>${esc(selected.name)}</p><form id="refuel" data-meters="${esc(JSON.stringify(meters))}">${Object.keys(meterLabels).filter(k=>meters[k]).map(k=>`<div class="row"><span>${meterLabels[k]} ANTERIOR</span><b class="reading" data-previous="${k}">${selected.record_count===0&&!queue.some(r=>r.fleet===selected.id)?'SEM REGISTRO':num(p[k])}</b></div><label>${meterLabels[k]} ATUAL<input name="${k}" type="number" min="${p[k]}" max="1000000000" step="0.01" inputmode="decimal" required value="${esc(draft[k]??'')}" placeholder="INFORME A LEITURA ATUAL"></label>`).join('')}<label>LITROS ABASTECIDOS<input name="liters" type="number" min="0.01" max="1000000000" step="0.01" inputmode="decimal" required value="${esc(draft.liters??'')}" placeholder="0,00"></label><p id="form-error" class="error" role="alert"></p><button class="primary" id="save" type="submit">${editId?'CORRIGIR E ENVIAR':'SALVAR ABASTECIMENTO'}</button></form></section>`}
async function choose(id){const fleet=session.fleets.find(f=>f.id===String(id).trim().toUpperCase()&&f.active);if(!fleet){message='Frota não encontrada no catálogo. Conecte o aplicativo para atualizar.';updatePanels();return}if(selected?.id!==fleet.id){if(Object.keys(draft).some(k=>k!=='fleet')&&!confirm('Trocar a frota e limpar o rascunho atual?'))return;draft={fleet:fleet.id};editId=null}selected=fleet;draft.fleet=fleet.id;message='';await saveDraft();render()}
async function scan(){if(!Capacitor.isNativePlatform())return manual();try{const result=await CapacitorBarcodeScanner.scanBarcode({hint:0,scanInstructions:'APONTE PARA O QR CODE DA FROTA',scanText:'LER QR CODE',cameraDirection:1,scanOrientation:1,cancelButtonAccessibilityLabel:'Cancelar leitura',torchButtonOnAccessibilityLabel:'Desligar lanterna',torchButtonOffAccessibilityLabel:'Ligar lanterna',android:{scanningLibrary:'zxing'}});if(result.ScanResult)await choose(readFleetQr(result.ScanResult))}catch(e){message=e.message?.includes('QR Code')?e.message:'Não foi possível ler. Permita o uso da câmera ou digite o código da frota.';updatePanels()}}
function manual(){const form=document.querySelector('#fleet-code');form.hidden=false;form.elements.fleet.focus();form.onsubmit=event=>{event.preventDefault();choose(form.elements.fleet.value)}}
async function submit(event){event.preventDefault();const button=document.querySelector('#save'),error=document.querySelector('#form-error');button.disabled=true;error.textContent='';try{const values=Object.fromEntries(new FormData(event.target)),meters=fields(selected),p=previous(selected),old=editId?queue.find(r=>r.id===editId):null;const record={id:editId||crypto.randomUUID(),userId:session.user.id,operator:session.user.name,fleet:selected.id,measuredFields:meters,liters:Number(values.liters),date:old?.date||today(),createdAt:old?.createdAt||new Date().toISOString()};for(const k of Object.keys(meterLabels))if(meters[k]){if(values[k]===''||values[k]===undefined)throw Error('Informe '+meterLabels[k]+'.');record[k]=Number(values[k]);if(!Number.isFinite(record[k])||record[k]<p[k]||record[k]>1e9)throw Error(meterLabels[k]+' deve ser no mínimo '+num(p[k])+'.')}if(!Number.isFinite(record.liters)||record.liters<=0||record.liters>1e9)throw Error('Informe litros maiores que zero.');await op('queue','readwrite',s=>s.put(record));draft={};selected=null;editId=null;await put(key('draft'),{});queue=(await op('queue','readonly',s=>s.getAll())).filter(r=>r.userId===session.user.id).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));message='Salvo no celular. Aguardando confirmação do envio.';render();sync()}catch(e){error.textContent=e.message;button.disabled=false}}
async function sync(){if(busy||!session||needsLogin)return;busy=true;updatePanels();try{const fresh=await api('session');if(fresh.user.id!==session.user.id){needsLogin=true;throw Error('Entre na conta original para enviar os registros pendentes.')}session={...fresh,cachedAt:new Date().toISOString()};await put('last-session',session);const blockedFleets=new Set();for(const record of [...queue]){if(record.error){blockedFleets.add(record.fleet);continue}if(blockedFleets.has(record.fleet))continue;try{const receipt=await api('mobile-submit',{method:'POST',body:JSON.stringify(record)});if(receipt?.id!==record.id)throw Error('O recebimento ainda não foi confirmado.');await op('queue','readwrite',s=>s.delete(record.id));queue=queue.filter(r=>r.id!==record.id);const fleet=session.fleets.find(f=>f.id===record.fleet);if(fleet){fleet.record_count=Math.max(1,Number(fleet.record_count||0));fleet.last_record_at=record.createdAt;for(const k of Object.keys(meterLabels))if(record[k]!==undefined)fleet['last_'+k]=Math.max(Number(fleet['last_'+k]||0),record[k]);}message='Abastecimento enviado para a administração.';await put('last-session',session)}catch(e){if(e.status===422||e.status===409){blockedFleets.add(record.fleet);record.error=e.message;await op('queue','readwrite',s=>s.put(record));const fleet=session.fleets.find(f=>f.id===record.fleet);if(fleet&&e.data?.readings)for(const k of Object.keys(meterLabels))fleet['last_'+k]=Math.max(Number(fleet['last_'+k]||0),Number(e.data.readings[k]||0));if(fleet&&e.data?.meterFields)fleet.meter_fields=e.data.meterFields;await put('last-session',session)}else throw e}}if(selected)selected=session.fleets.find(f=>f.id===selected.id)||selected;connected=true}catch(e){connected=false;if(e.status===401||e.status===403){try{await fieldApi('session');needsLogin=true;message='Entre novamente. Os registros continuam salvos neste aparelho.'}catch{}}}finally{busy=false;if(needsLogin)login(message);else updatePanels()}}
function login(error=''){logout.hidden=true;app.innerHTML=`<h1>ENTRAR</h1><form id="login"><label>USUÁRIO<input name="username" autocomplete="username" autocapitalize="none" required></label><label>SENHA<input name="password" type="password" autocomplete="current-password" required></label><p id="login-error" class="error" role="alert">${esc(error)}</p><button class="primary" type="submit">ENTRAR</button></form>`;document.querySelector('#login').onsubmit=async event=>{event.preventDefault();const button=event.target.querySelector('button');button.disabled=true;try{if(!isConfigured())throw Error('Aplicativo sem configuração do banco.');const data=new FormData(event.target);await signIn(data.get('username'),data.get('password'));session={...await api('session'),cachedAt:new Date().toISOString()};await put('last-session',session);needsLogin=false;connected=true;await load();render();sync()}catch(e){document.querySelector('#login-error').textContent=e.message;button.disabled=false}}}
logout.onclick=async()=>{if(queue.length){message='Envie ou corrija os registros pendentes antes de sair.';updatePanels();return}await saveDraft();await signOut();await put('last-session',null);session=null;selected=null;draft={};login()};
window.addEventListener('online',sync);document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync()});
async function boot(){try{db=await openDB();session=await get('last-session');if(session){await load();render();sync()}else login();setInterval(sync,15000)}catch{app.innerHTML='<p class="error">Não foi possível abrir o armazenamento do aplicativo.</p>'}}
boot();
