import {Capacitor,registerPlugin} from '@capacitor/core';
import {config} from '../web/config.js';
const OfflineSync=registerPlugin('OfflineSync');
let nativeConfigured=false,mirrorBusy=false;
import {parseNumber,formatInput,recorderBase,litersFromRecorder} from './operations.js';
import {CapacitorBarcodeScanner} from '@capacitor/barcode-scanner';
import {api,fieldApi,signIn,signOut,isConfigured} from '../web/backend.js';
import {readFleetQr,defaultMeters,meterLabels} from './fleet-qr.js';
const app=document.querySelector('#app'),logout=document.querySelector('#logout');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:2});
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo'}).format(new Date());
let screen='context',context={},mode='manual';
let db,session,draft={},queue=[],selected=null,busy=false,connected=false,needsLogin=false,editId=null,message='';
async function openDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open('abencoada-diesel-mobile',1);req.onupgradeneeded=()=>{req.result.createObjectStore('meta',{keyPath:'key'});req.result.createObjectStore('queue',{keyPath:'id'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
function op(store,mode,fn){return new Promise((resolve,reject)=>{const tx=db.transaction(store,mode),req=fn(tx.objectStore(store));let value;req.onsuccess=()=>value=req.result;tx.oncomplete=()=>resolve(value);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
const get=async key=>(await op('meta','readonly',s=>s.get(key)))?.value;
const put=(key,value)=>op('meta','readwrite',s=>s.put({key,value}));
const key=name=>session.user.id+':'+name;
const fields=f=>f.meter_fields||defaultMeters(f.type);
function previous(f){const editing=editId?queue.find(r=>r.id===editId):null;const values={km:Number(f.last_km||0),engine:Number(f.last_engine||0),elevator:Number(f.last_elevator||0)};for(const r of queue)if(r.fleet===f.id&&r.id!==editId&&!r.error&&(!editing||r.createdAt<editing.createdAt))for(const k of Object.keys(values))if(r[k]!==undefined)values[k]=Math.max(values[k],r[k]);return values}
async function load(){queue=(await op('queue','readonly',s=>s.getAll())).filter(r=>r.userId===session.user.id).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));context=await get(key('context'))||{};draft=await get(key('draft'))||{};selected=session.fleets.find(f=>f.id===draft.fleet&&f.active)||null}
async function saveDraft(){await put(key('draft'),draft)}
function statusHTML(){return `<p class="muted">${connected?'CONECTADO':'ÚLTIMOS DADOS SALVOS NO CELULAR'}${session.cachedAt?' · '+esc(new Date(session.cachedAt).toLocaleString('pt-BR')):''}</p>${message?`<p class="success" role="status">${esc(message)}</p>`:''}`}
function pendingHTML(){return queue.length?`<section class="card pending"><div class="row"><b>${queue.length} PENDENTE${queue.length>1?'S':''}</b><button class="secondary" id="retry" ${busy?'disabled':''}>${busy?'ENVIANDO…':'ENVIAR'}</button></div>${queue.filter(r=>r.error).map(r=>`<div class="card"><b>${r.kind==='transfer'?'TRANSFERÊNCIA':r.kind==='occurrence'?'OCORRÊNCIA':'FROTA '+esc(r.fleet)}</b><p class="error">${esc(r.error)}</p><button class="secondary" data-correct="${r.id}">CONFERIR E CORRIGIR</button></div>`).join('')}</section>`:''}
function bindPending(){const retry=document.querySelector('#retry');if(retry)retry.onclick=sync;document.querySelectorAll('[data-correct]').forEach(b=>b.onclick=async()=>{const r=queue.find(r=>r.id===b.dataset.correct);if(!r)return;editId=r.id;draft=Object.fromEntries(Object.entries(r).map(([k,v])=>[k,typeof v==='number'?v.toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2}):v]));context={localCode:r.localCode,materialCode:r.materialCode};mode=r.mode||'manual';screen=r.kind==='occurrence'?'occurrence':r.kind==='transfer'?'transfer':'refuel';selected=session.fleets.find(f=>f.id===r.fleet);await saveDraft();render()})}
function updatePanels(){const form=document.querySelector('#refuel');if(form&&selected){if(form.dataset.meters!==JSON.stringify(fields(selected))){render();return}const p=previous(selected);for(const k of Object.keys(meterLabels)){const label=document.querySelector('[data-previous="'+k+'"]');if(label)label.textContent=selected.record_count===0&&!selected.gmais_readings&&!queue.some(r=>r.fleet===selected.id)?'SEM REGISTRO':num(p[k]);}}updateCalculated();const baseline=document.querySelector('#recorder-base');if(baseline){const value=recorderBase(session.locations||[],queue,context.localCode,context.materialCode,editId);baseline.textContent=value===null?'SEM LEITURA INICIAL':num(value)}const status=document.querySelector('#status'),pending=document.querySelector('#pending');if(status)status.innerHTML=statusHTML();if(pending){pending.innerHTML=pendingHTML();bindPending()}}
function render(){if(!session||needsLogin)return login();return renderFlow()}
function decimal(name,label,value=''){return `<label>${label}<input name="${name}" inputmode="numeric" data-decimal required value="${esc(value)}" placeholder="0,00" autocomplete="off"></label>`}
function formHTML(){const p=previous(selected),meters=fields(selected),base=recorderBase(session.locations||[],queue,context.localCode,context.materialCode,editId);return `<section class="card"><h2>FROTA ${esc(selected.id)}</h2><p>${esc(selected.name)}</p>${selected.gmais_readings?`<p class="muted">REFERÊNCIA GMAIS: ${num(selected.gmais_readings.reading)} · ${esc(selected.gmais_readings.recordedAt||'DATA NÃO INFORMADA')}</p>`:''}<form id="refuel" data-meters="${esc(JSON.stringify(meters))}">${Object.keys(meterLabels).filter(k=>meters[k]).map(k=>`<div class="row"><span>${meterLabels[k]} ANTERIOR</span><b class="reading" data-previous="${k}">${num(p[k])}</b></div>${decimal(k,meterLabels[k]+' ATUAL',draft[k]??'')}`).join('')}${mode==='recorder'?`<p>REGISTRADORA ANTERIOR<br><b class="reading" id="recorder-base">${base===null?'SEM LEITURA INICIAL':num(base)}</b></p>${decimal('recorderEnd','FINAL DA REGISTRADORA',draft.recorderEnd??'')}<div class="liters-result"><span>LITROS ABASTECIDOS</span><strong id="calculated-liters">—</strong></div>`:decimal('liters','LITROS ABASTECIDOS',draft.liters??'')}<p id="form-error" class="error" role="alert"></p><button class="primary" id="save" type="submit">${editId?'CORRIGIR E ENVIAR':'SALVAR ABASTECIMENTO'}</button></form></section>`}
async function choose(id){const fleet=session.fleets.find(f=>f.id===String(id).trim().toUpperCase()&&f.active);if(!fleet){message='Frota não encontrada no catálogo. Conecte o aplicativo para atualizar.';updatePanels();return}if(selected?.id!==fleet.id){if(Object.keys(draft).some(k=>k!=='fleet')&&!confirm('Trocar a frota e limpar o rascunho atual?'))return;draft={fleet:fleet.id};editId=null}selected=fleet;draft.fleet=fleet.id;screen='refuel';message='';await saveDraft();render()}
async function scan(){if(!Capacitor.isNativePlatform())return manual();try{const result=await CapacitorBarcodeScanner.scanBarcode({hint:0,scanInstructions:'APONTE PARA O QR CODE DA FROTA',scanText:'LER QR CODE',cameraDirection:1,scanOrientation:1,cancelButtonAccessibilityLabel:'Cancelar leitura',torchButtonOnAccessibilityLabel:'Desligar lanterna',torchButtonOffAccessibilityLabel:'Ligar lanterna',android:{scanningLibrary:'zxing'}});if(result.ScanResult)await choose(readFleetQr(result.ScanResult))}catch(e){message=e.message?.includes('QR Code')?e.message:'Não foi possível ler. Permita o uso da câmera ou digite o código da frota.';updatePanels()}}
function manual(){const form=document.querySelector('#fleet-code');form.hidden=false;form.elements.fleet.focus();form.onsubmit=event=>{event.preventDefault();choose(form.elements.fleet.value)}}
async function submit(event){event.preventDefault();const button=document.querySelector('#save'),error=document.querySelector('#form-error');button.disabled=true;error.textContent='';try{const values=Object.fromEntries(new FormData(event.target)),meters=fields(selected),p=previous(selected),old=editId?queue.find(r=>r.id===editId):null;const record={id:editId||crypto.randomUUID(),kind:'refuel',mode,userId:session.user.id,operator:session.user.name,fleet:selected.id,localCode:context.localCode,materialCode:context.materialCode,measuredFields:meters,date:old?.date||today(),createdAt:old?.createdAt||new Date().toISOString()};for(const k of Object.keys(meterLabels))if(meters[k]){record[k]=parseNumber(values[k]);if(record[k]<p[k])throw Error(meterLabels[k]+' deve ser no mínimo '+num(p[k])+'.')}if(mode==='recorder'){record.recorderStart=recorderBase(session.locations||[],queue,context.localCode,context.materialCode,editId);record.recorderEnd=parseNumber(values.recorderEnd);record.liters=litersFromRecorder(record.recorderStart,record.recorderEnd)}else record.liters=parseNumber(values.liters);if(record.liters<=0)throw Error('Informe litros maiores que zero.');await enqueue(record);draft={};selected=null;editId=null;await put(key('draft'),{});screen='menu';message='SALVO NO CELULAR: '+num(record.liters)+' LITROS. AGUARDANDO ENVIO.';render();sync()}catch(e){error.textContent=e.message;button.disabled=false}}
async function enqueue(record){await op('queue','readwrite',s=>s.put(record));queue=(await op('queue','readonly',s=>s.getAll())).filter(r=>r.userId===session.user.id).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));await mirrorQueue().catch(()=>{})}
async function sync(){if(busy||!session||needsLogin)return;busy=true;updatePanels();try{await mirrorQueue();const fresh=await api('session');if(fresh.user.id!==session.user.id){needsLogin=true;throw Error('Entre na conta original para enviar os registros pendentes.')}session={...fresh,cachedAt:new Date().toISOString()};await put('last-session',session);await configureNative();const blockedFleets=new Set();for(const record of [...queue]){const dependency=record.mode==='recorder'?'local:'+record.localCode+':'+record.materialCode:'fleet:'+record.fleet;if(record.error){blockedFleets.add(dependency);continue}if(blockedFleets.has(dependency))continue;try{const receipt=await api(record.kind?'operation-submit':'mobile-submit',{method:'POST',body:JSON.stringify(record)});if(receipt?.id!==record.id)throw Error('O recebimento ainda não foi confirmado.');await op('queue','readwrite',s=>s.delete(record.id));queue=queue.filter(r=>r.id!==record.id);if(record.kind==='refuel'){const l=(session.locations||[]).find(l=>l.local_code===record.localCode&&l.material_code===record.materialCode);if(l)l.last_meter=record.mode==='recorder'?record.recorderEnd:null;else(session.locations??=[]).push({local_code:record.localCode,material_code:record.materialCode,last_meter:record.mode==='recorder'?record.recorderEnd:null})}const fleet=session.fleets.find(f=>f.id===record.fleet);if(fleet){fleet.record_count=Math.max(1,Number(fleet.record_count||0));fleet.last_record_at=record.createdAt;for(const k of Object.keys(meterLabels))if(record[k]!==undefined)fleet['last_'+k]=Math.max(Number(fleet['last_'+k]||0),record[k]);}message='REGISTRO ENVIADO PARA A ADMINISTRAÇÃO.';await put('last-session',session)}catch(e){if(e.status===422||e.status===409){blockedFleets.add(dependency);record.error=e.message;await op('queue','readwrite',s=>s.put(record));const fleet=session.fleets.find(f=>f.id===record.fleet);if(fleet&&e.data?.readings)for(const k of Object.keys(meterLabels))fleet['last_'+k]=Math.max(Number(fleet['last_'+k]||0),Number(e.data.readings[k]||0));if(e.data?.recorder!==undefined){const l=(session.locations||[]).find(l=>l.local_code===record.localCode&&l.material_code===record.materialCode);if(l)l.last_meter=e.data.recorder;else(session.locations??=[]).push({local_code:record.localCode,material_code:record.materialCode,last_meter:e.data.recorder})}if(fleet&&e.data?.meterFields)fleet.meter_fields=e.data.meterFields;await put('last-session',session)}else throw e}}if(selected)selected=session.fleets.find(f=>f.id===selected.id)||selected;connected=true}catch(e){connected=false;if(e.status===401||e.status===403){try{await fieldApi('session');needsLogin=true;message='Entre novamente. Os registros continuam salvos neste aparelho.'}catch{}}}finally{busy=false;await mirrorQueue().catch(()=>{});if(needsLogin)login(message);else updatePanels()}}
function login(error=''){logout.hidden=true;app.innerHTML=`<h1>ENTRAR</h1><form id="login"><label>USUÁRIO<input name="username" autocomplete="username" autocapitalize="none" required></label><label>SENHA<input name="password" type="password" autocomplete="current-password" required></label><p id="login-error" class="error" role="alert">${esc(error)}</p><button class="primary" type="submit">ENTRAR</button></form>`;document.querySelector('#login').onsubmit=async event=>{event.preventDefault();const button=event.target.querySelector('button');button.disabled=true;try{if(!isConfigured())throw Error('Aplicativo sem configuração do banco.');const data=new FormData(event.target);await signIn(data.get('username'),data.get('password'));session={...await api('session'),cachedAt:new Date().toISOString()};await put('last-session',session);needsLogin=false;nativeConfigured=false;connected=true;screen='context';await load();render();sync()}catch(e){document.querySelector('#login-error').textContent=e.message;button.disabled=false}}}
logout.onclick=async()=>{if(queue.length){message='Envie ou corrija os registros pendentes antes de sair.';updatePanels();return}await saveDraft();await signOut();await put('last-session',null);session=null;selected=null;draft={};login()};
window.addEventListener('online',sync);document.addEventListener('visibilitychange',()=>{if(!document.hidden)sync()});
async function boot(){try{db=await openDB();session=await get('last-session');if(session){await load();render();sync()}else login();setInterval(sync,15000)}catch{app.innerHTML='<p class="error">Não foi possível abrir o armazenamento do aplicativo.</p>'}}
boot();

function renderFlow(){
 logout.hidden=false;const header=`<h1>${screen==='context'?'LOCAL E MATERIAL':screen==='transfer'?'TRANSFERÊNCIA':screen==='occurrence'?'OCORRÊNCIA':'ABASTECE'}</h1><div class="worker">${esc(session.user.name)}</div>${context.localCode&&screen!=='context'?`<p class="context">LOCAL ${esc(context.localCode)} · MATERIAL ${esc(context.materialCode)}</p>`:''}<div id="status">${statusHTML()}</div>`;
 let content='';
 if(screen==='context')content=`<form id="context-form"><label>CÓDIGO DO LOCAL<input name="localCode" inputmode="numeric" pattern="[0-9]{1,30}" required maxlength="30" value="${esc(context.localCode||'')}" list="locations"></label><datalist id="locations">${[...new Map((session.locations||[]).map(l=>[l.local_code,l])).values()].map(l=>`<option value="${esc(l.local_code)}">${esc(l.name)}</option>`).join('')}</datalist><label>CÓDIGO DO MATERIAL<input name="materialCode" inputmode="numeric" pattern="[0-9]{1,30}" required maxlength="30" value="${esc(context.materialCode||'')}" list="materials"></label><datalist id="materials">${[...new Map((session.materials||session.locations||[]).map(l=>[l.material_code,l])).values()].map(l=>`<option value="${esc(l.material_code)}">${esc(l.material_name)}</option>`).join('')}</datalist><button class="primary">CONTINUAR</button></form>`;
 else if(screen==='menu')content=`<button class="primary" data-screen="methods">ABASTECIMENTO</button><button class="primary" data-screen="transfer">TRANSFERÊNCIA</button><button class="secondary" data-screen="occurrence">OBSERVAÇÃO / OCORRÊNCIA</button><button class="secondary" data-screen="context">ALTERAR LOCAL E MATERIAL</button>`;
 else if(screen==='methods')content=`<button class="primary" id="qr-method">QR CODE</button><button class="primary" id="manual-method">DIGITAR DADOS DO ABASTECIMENTO</button>`;
 else if(screen==='scan')content=`${mode==='recorder'?'<button class="primary" id="scan">ABRIR CÂMERA</button>':''}<form id="fleet-code"><label>CÓDIGO DA FROTA<input name="fleet" inputmode="numeric" pattern="[0-9]{1,30}" required></label><button class="secondary">SELECIONAR FROTA</button></form>`;
 else if(screen==='refuel')content=selected?formHTML():'';
 else if(screen==='transfer')content=`<form id="transfer-form"><p>LOCAL ATUAL: <b>${esc(context.localCode)}</b></p><label>NOVO CÓDIGO DO LOCAL<input name="destination" inputmode="numeric" pattern="[0-9]{1,30}" required maxlength="30" value="${esc(draft.destination||'')}"></label><p class="error" id="form-error"></p><button class="primary">CONFIRMAR TRANSFERÊNCIA</button></form>`;
 else if(screen==='occurrence')content=`<form id="occurrence-form"><label>OBSERVAÇÃO OU OCORRÊNCIA<textarea name="notes" required minlength="3" maxlength="2000" rows="5">${esc(draft.notes||'')}</textarea></label><p class="error" id="form-error"></p><button class="primary">SALVAR OCORRÊNCIA</button></form>`;
 app.innerHTML=header+content+(screen!=='menu'&&screen!=='context'?'<button class="secondary" data-screen="menu">VOLTAR AO MENU</button>':'')+`<div id="pending">${pendingHTML()}</div>`;
 document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>{screen=b.dataset.screen;editId=null;render()});
 const ctx=document.querySelector('#context-form');if(ctx)ctx.onsubmit=async e=>{e.preventDefault();context=Object.fromEntries(new FormData(e.target));await put(key('context'),context);screen='menu';render()};
 const qr=document.querySelector('#qr-method');if(qr)qr.onclick=()=>{mode='recorder';editId=null;selected=null;screen='scan';render()};const man=document.querySelector('#manual-method');if(man)man.onclick=()=>{mode='manual';editId=null;selected=null;screen='scan';render()};
 const scanButton=document.querySelector('#scan');if(scanButton)scanButton.onclick=scan;
 const fleetCode=document.querySelector('#fleet-code');if(fleetCode)fleetCode.onsubmit=e=>{e.preventDefault();choose(fleetCode.elements.fleet.value)};
 const refuel=document.querySelector('#refuel');if(refuel){refuel.onsubmit=submit;refuel.oninput=e=>{if(e.target.hasAttribute('data-decimal'))e.target.value=formatInput(e.target.value);draft={...draft,...Object.fromEntries(new FormData(refuel))};saveDraft().catch(()=>{});updateCalculated()};updateCalculated()}
 const transfer=document.querySelector('#transfer-form');if(transfer)transfer.onsubmit=e=>saveEvent(e,'transfer');const occurrence=document.querySelector('#occurrence-form');if(occurrence)occurrence.onsubmit=e=>saveEvent(e,'occurrence');
 document.querySelectorAll('input[inputmode="numeric"]:not([data-decimal])').forEach(input=>input.oninput=()=>{input.value=input.value.replace(/\D/g,'')});bindPending();
}
function updateCalculated(){const result=document.querySelector('#calculated-liters');if(!result)return;try{result.textContent=num(litersFromRecorder(recorderBase(session.locations||[],queue,context.localCode,context.materialCode,editId),parseNumber(document.querySelector('[name="recorderEnd"]').value)))+' L'}catch{result.textContent='—'}}
async function saveEvent(e,kind){e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{const values=Object.fromEntries(new FormData(e.target));if(kind==='transfer'&&values.destination===context.localCode)throw Error('Informe um local diferente do atual.');const record={id:editId||crypto.randomUUID(),kind,userId:session.user.id,localCode:context.localCode,materialCode:context.materialCode,createdAt:new Date().toISOString(),...values};await enqueue(record);if(kind==='transfer'){context.localCode=values.destination;await put(key('context'),context)}editId=null;draft={};await saveDraft();screen='menu';message='SALVO NO CELULAR. AGUARDANDO ENVIO.';render();sync()}catch(error){document.querySelector('#form-error').textContent=error.message;button.disabled=false}}
async function configureNative(){
 if(!Capacitor.isNativePlatform()||nativeConfigured)return;
 let deviceId=await get('device-id');if(!deviceId){deviceId=crypto.randomUUID();await put('device-id',deviceId)}
 const lease=await api('device-register',{method:'POST',body:JSON.stringify({deviceId})});
 await OfflineSync.configure({userId:session.user.id,token:lease.token,url:config.url,apikey:config.publishableKey});nativeConfigured=true;await mirrorQueue();
}
function sameRecord(a,b){if(a===b)return true;if(!a||!b||typeof a!=='object'||typeof b!=='object')return false;const keys=Object.keys(a);return keys.length===Object.keys(b).length&&keys.every(k=>sameRecord(a[k],b[k]))}
async function mirrorQueue(){
 if(!Capacitor.isNativePlatform()||!session||mirrorBusy)return;mirrorBusy=true;
 try{const result=await OfflineSync.mirror({userId:session.user.id,queue});
  const ids=[];for(const ack of result.acks||[]){if(ack.userId!==session.user.id)continue;const sent=queue.find(r=>r.id===ack.id);if(sent){const fleet=session.fleets.find(f=>f.id===sent.fleet);if(fleet)for(const k of Object.keys(meterLabels))if(sent[k]!==undefined)fleet['last_'+k]=Math.max(Number(fleet['last_'+k]||0),sent[k]);const local=(session.locations||[]).find(l=>l.local_code===sent.localCode&&l.material_code===sent.materialCode);if(local&&sent.kind==='refuel')local.last_meter=sent.mode==='recorder'?sent.recorderEnd:null;await put('last-session',session)}await op('queue','readwrite',s=>s.delete(ack.id));queue=queue.filter(r=>r.id!==ack.id);ids.push(ack.id)}
  if(ids.length)await OfflineSync.acknowledge({userId:session.user.id,ids});
  for(const failure of result.errors||[]){const record=queue.find(r=>r.id===failure.id);if(!record||!sameRecord(record,JSON.parse(failure.record||'null')))continue;record.error=failure.message;await op('queue','readwrite',s=>s.put(record));if(failure.data?.status===403)nativeConfigured=false;}
 }finally{mirrorBusy=false}
}
document.addEventListener('click',e=>{if(e.target.closest('button')&&!e.target.closest('button').disabled)navigator.vibrate?.(25)});
