import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role service_role;create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.uid',true),'')::uuid$$;create function auth.jwt() returns jsonb language sql as $$select jsonb_build_object('email',current_setting('test.email',true))$$;grant usage on schema auth to authenticated;grant execute on all functions in schema auth to authenticated;`);
await db.exec(await readFile('supabase/schema.sql','utf8'));
await db.exec(await readFile('supabase/fleets.sql','utf8'));
assert.equal((await db.query('select count(*)::int n from fleets')).rows[0].n,246);
const ids=['00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002','00000000-0000-4000-8000-000000000003'];
await db.query(`insert into auth.users values($1),($2),($3)`,ids);
await db.exec(`insert into members values('gestor@example.com','Gestor','admin'),('operador@example.com','João','operator');insert into fleets values('QA','Teste','Trator',true);`);
await db.exec(await readFile('supabase/usernames.sql','utf8'));
await db.exec(await readFile('supabase/field-access.sql','utf8'));
await db.exec(await readFile('supabase/mobile.sql','utf8'));
assert.equal((await db.query("select username from members where email='gestor@example.com'")).rows[0].username,'gestor');
async function who(i,email){await db.exec('reset role');await db.query("select set_config('test.uid',$1,false),set_config('test.email',$2,false)",[ids[i],email]);await db.exec('set role authenticated')}
async function rpc(name,payload){return (await db.query(`select public.${name}($1::jsonb) result`,[JSON.stringify(payload)])).rows[0].result}
await who(1,'operador@example.com');
const base={id:crypto.randomUUID(),fleet:'QA',date:'2026-10-07',engine:100,elevator:200,km:300,start:0,end:50,liters:50,operator:'FALSO',signature:'FALSA',notes:'',createdAt:new Date().toISOString()};
assert.equal((await rpc('diesel_submit',base)).id,base.id);
assert.equal((await rpc('diesel_submit',base)).duplicate,true);
for(const key of ['engine','elevator','km'])assert.equal((await rpc('diesel_submit',{...base,id:crypto.randomUUID(),[key]:base[key]-1})).status,422);
for(const key of ['engine','elevator','km','start','end','liters']){const r={...base,id:crypto.randomUUID()};delete r[key];assert.equal((await rpc('diesel_submit',r)).status,422)}
assert.equal((await rpc('diesel_submit',{...base,id:crypto.randomUUID(),liters:0})).status,422);
assert.equal((await rpc('diesel_submit',{...base,id:crypto.randomUUID(),end:0})).status,422);
assert.ok((await rpc('diesel_submit',{...base,id:crypto.randomUUID()})).id);
assert.equal((await rpc('diesel_admin_save',{action:'member',email:'novo@example.com',name:'Novo',role:'admin'})).status,403);
await assert.rejects(()=>db.query("insert into fleets(id,name,type) values('ILEGAL','Teste','Outro')"),/permission denied/);
await who(0,'gestor@example.com');
assert.ok((await rpc('diesel_submit',{...base,id:crypto.randomUUID(),engine:101})).id);
let data=(await db.query('select public.diesel_records() result')).rows[0].result;
assert.equal(data.records.length,3);assert.equal(data.records.find(r=>r.id===base.id).signature,'João');assert.equal(data.records.find(r=>r.id===base.id).operator,'João');
assert.equal((await rpc('diesel_submit',{...base,id:crypto.randomUUID()})).status,422);
await who(1,'operador@example.com');
data=(await db.query('select public.diesel_records() result')).rows[0].result;assert.equal(data.records.length,2);
await who(2,'naoautorizado@example.com');
assert.equal((await rpc('diesel_submit',{...base,id:crypto.randomUUID()})).status,403);
assert.equal((await db.query('select public.diesel_session() result')).rows[0].result.status,403);
await who(0,'gestor@example.com');
assert.equal((await rpc('diesel_admin_save',{action:'member-username',email:'gestor@example.com',username:'GESTOR.CAMPO'})).ok,true);
assert.equal((await rpc('diesel_admin_save',{action:'member-username',email:'operador@example.com',username:'gestor.campo'})).status,422);
assert.equal((await rpc('diesel_admin_save',{action:'member-username',email:'operador@example.com',username:'ab'})).status,422);
await who(1,'operador@example.com');
assert.equal((await rpc('diesel_admin_save',{action:'member-username',email:'operador@example.com',username:'outro'})).status,403);
await assert.rejects(()=>db.query("select diesel_login_target('operador','test')"),/permission denied/);
await db.exec('reset role;set role service_role');
for(let i=0;i<10;i++)assert.equal((await db.query("select diesel_login_target('operador','test') result")).rows[0].result.email,'operador@example.com');
assert.equal((await db.query("select diesel_login_target('operador','test') result")).rows[0].result.status,429);
assert.equal((await db.query("select diesel_login_target('desconhecido','test') result")).rows[0].result.email,null);
await db.exec('reset role;set role anon');
const catalog=(await db.query('select diesel_field_session() result')).rows[0].result;
assert.ok(catalog.fleets.length);assert.deepEqual(Object.keys(catalog).sort(),['fleets','rules']);
const guest={...base,id:crypto.randomUUID(),engine:101,operator:'  José   do Campo  ',submissionKey:crypto.randomUUID(),userId:ids[0],signature:'GESTOR',role:'admin'};
assert.equal((await rpc('diesel_field_submit',guest)).id,guest.id);
assert.equal((await rpc('diesel_field_submit',guest)).duplicate,true);
assert.equal((await rpc('diesel_field_submit',{...guest,submissionKey:crypto.randomUUID()})).status,409);
for(const key of ['engine','elevator','km'])assert.equal((await rpc('diesel_field_submit',{...guest,id:crypto.randomUUID(),[key]:0})).status,422);
for(const operator of ['', '1', '123', null])assert.equal((await rpc('diesel_field_submit',{...guest,id:crypto.randomUUID(),operator})).status,422);
assert.equal((await rpc('diesel_field_submit',{...guest,id:crypto.randomUUID(),submissionKey:null})).status,422);
for(const key of ['engine','elevator','km','start','end','liters']){const r={...guest,id:crypto.randomUUID()};delete r[key];assert.equal((await rpc('diesel_field_submit',r)).status,422)}
await assert.rejects(()=>db.query('select * from records'),/permission denied/);
await assert.rejects(()=>db.query('select diesel_admin()'),/permission denied/);
await assert.rejects(()=>db.query("select private.submit_record('{}','Falso',null,'declared',null)"),/permission denied/);
await who(1,'operador@example.com');
assert.equal((await db.query('select diesel_records() result')).rows[0].result.records.length,2);
await who(0,'gestor@example.com');
const saved=(await db.query('select diesel_records($1) result',[guest.id])).rows[0].result;
assert.equal(saved.operator,'José do Campo');assert.equal(saved.signature,'José do Campo');assert.equal(saved.signature_source,'declared');assert.equal(saved.user_id,null);
await db.exec('reset role;set role anon');
await assert.rejects(()=>db.query("select diesel_login_target('operador','test')"),/permission denied/);
await assert.rejects(()=>db.query('select public.diesel_session()'),/permission denied/);
await assert.rejects(()=>db.query("select diesel_mobile_submit('{}')"),/permission denied/);
await who(1,'operador@example.com');
const quick={id:crypto.randomUUID(),fleet:'QA',date:base.date,createdAt:base.createdAt,liters:25,engine:150,measuredFields:{km:false,engine:true,elevator:false},operator:'FALSO',signature:'FALSA',userId:ids[0]};
const receipt=await rpc('diesel_mobile_submit',quick);assert.equal(receipt.id,quick.id);assert.equal(receipt.previous.engine,101);
assert.equal((await rpc('diesel_mobile_submit',quick)).duplicate,true);
assert.equal((await rpc('diesel_mobile_submit',{...quick,id:crypto.randomUUID(),engine:149})).status,422);
assert.equal((await rpc('diesel_mobile_submit',{...quick,id:crypto.randomUUID(),engine:undefined})).status,422);
assert.equal((await rpc('diesel_mobile_submit',{...quick,id:crypto.randomUUID(),liters:0})).status,422);
assert.equal((await rpc('diesel_mobile_submit',{...quick,id:crypto.randomUUID(),measuredFields:{km:true,engine:false,elevator:false}})).status,422);
await who(0,'gestor@example.com');
const quickSaved=(await db.query('select diesel_records($1) result',[quick.id])).rows[0].result;
assert.equal(quickSaved.operator,'João');assert.equal(quickSaved.user_id,ids[1]);assert.equal(quickSaved.capture_mode,'quick');assert.equal(quickSaved.start,null);assert.equal(quickSaved.end,null);assert.equal(quickSaved.km,300);assert.equal(quickSaved.previous_readings.km,300);assert.equal(quickSaved.previous_readings.engine,101);assert.equal(quickSaved.engine,150);
assert.equal((await rpc('diesel_admin_save',{action:'fleet-meters',id:'QA',meterFields:{km:false,engine:false,elevator:false}})).status,422);
assert.equal((await rpc('diesel_admin_save',{action:'fleet-meters',id:'QA',meterFields:{km:true,engine:true,elevator:true}})).ok,true);
await who(1,'operador@example.com');
assert.equal((await rpc('diesel_mobile_submit',{...quick,id:crypto.randomUUID(),engine:160})).status,422);
assert.equal((await rpc('diesel_admin_save',{action:'fleet-meters',id:'QA',meterFields:{km:true,engine:false,elevator:false}})).status,403);
assert.ok((await rpc('diesel_mobile_submit',{...quick,id:crypto.randomUUID(),engine:160,km:400,elevator:250,measuredFields:{km:true,engine:true,elevator:true}})).id);
await who(2,'naoautorizado@example.com');assert.equal((await rpc('diesel_mobile_submit',{...quick,id:crypto.randomUUID()})).status,403);
await db.close();console.log('Regras, permissões, catálogo e assinatura: testes aprovados.');
