import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {parseNumber,formatInput,recorderBase,litersFromRecorder} from '../mobile/operations.js';
assert.equal(formatInput('123456'),'1.234,56');assert.equal(parseNumber('1.234,56'),1234.56);assert.throws(()=>parseNumber(''));assert.equal(litersFromRecorder(100,125.12),25.12);assert.throws(()=>litersFromRecorder(null,125));assert.throws(()=>litersFromRecorder(100,100));
assert.equal(recorderBase([{local_code:'2',material_code:'9',last_meter:100}],[{id:'pending',kind:'refuel',mode:'recorder',localCode:'2',materialCode:'9',recorderEnd:150}], '2','9'),150);
const db=new PGlite();await db.exec(`create role service_role;create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql as $$select (nullif(current_setting('request.jwt.claims',true),'')::jsonb->>'sub')::uuid$$;create function auth.jwt() returns jsonb language sql as $$select nullif(current_setting('request.jwt.claims',true),'')::jsonb$$;grant usage on schema auth to authenticated,anon;grant execute on all functions in schema auth to authenticated,anon;`);
for(const f of ['schema','usernames','field-access','mobile','operations','background-sync','gmais-readings'])await db.exec(await readFile('supabase/'+f+'.sql','utf8'));
const user=crypto.randomUUID(),other=crypto.randomUUID();await db.query('insert into auth.users values($1),($2)',[user,other]);await db.exec("insert into members(email,name,role,username) values('admin@example.com','GESTOR','admin','gestor'),('worker@example.com','OPERADOR','operator','operador');insert into fleets(id,name,type,meter_fields) values('1001','TESTE','Trator','{\"km\":false,\"engine\":true,\"elevator\":false}');");
async function who(id,email,role='authenticated'){await db.exec('reset role');await db.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify({sub:id,email,role})]);await db.exec('set role '+role)}
async function rpc(name,payload){return(await db.query('select '+name+'($1::jsonb) result',[JSON.stringify(payload)])).rows[0].result}
await who(user,'admin@example.com');assert.ok((await rpc('diesel_operations_admin',{action:'location',localCode:'2',materialCode:'9',lastMeter:1000})).locations);const session=(await db.query('select diesel_session() result')).rows[0].result;assert.equal(session.locations[0].last_meter,1000);
await who(other,'worker@example.com');assert.equal((await rpc('diesel_operations_admin',null)).status,403);await assert.rejects(()=>db.query('select * from diesel_locations'),/permission denied/);
const r={id:crypto.randomUUID(),kind:'refuel',mode:'recorder',localCode:'2',materialCode:'9',fleet:'1001',date:'2026-10-09',createdAt:new Date().toISOString(),engine:100,measuredFields:{km:false,engine:true,elevator:false},recorderStart:1000,recorderEnd:1050,liters:50};
assert.equal((await rpc('diesel_operation_submit',r)).id,r.id);assert.equal((await rpc('diesel_operation_submit',r)).duplicate,true);assert.equal((await rpc('diesel_operation_submit',{...r,id:crypto.randomUUID()})).status,409);assert.equal((await rpc('diesel_operation_submit',{...r,id:crypto.randomUUID(),recorderStart:1050,recorderEnd:1100,engine:99})).status,422);
const transfer={id:crypto.randomUUID(),kind:'transfer',localCode:'2',materialCode:'9',destination:'208',createdAt:r.createdAt};assert.equal((await rpc('diesel_operation_submit',transfer)).id,transfer.id);assert.equal((await rpc('diesel_operation_submit',transfer)).duplicate,true);
const occurrence={...transfer,id:crypto.randomUUID(),kind:'occurrence',notes:'Bomba precisa de manutenção.'};assert.equal((await rpc('diesel_operation_submit',occurrence)).id,occurrence.id);assert.equal((await rpc('diesel_operation_submit',{...occurrence,id:crypto.randomUUID(),notes:''})).status,422);
const device=crypto.randomUUID();const lease=(await db.query('select diesel_device_register($1) result',[device])).rows[0].result;assert.ok(lease.token);await who(null,null,'anon');await assert.rejects(()=>db.query('select diesel_operations_admin()'),/permission denied/);await assert.rejects(()=>db.query('select diesel_device_register($1)',[device]),/permission denied/);
const bg={...r,id:crypto.randomUUID(),recorderStart:1050,recorderEnd:1110,liters:60,engine:110};const submit=async(token,payload)=>(await db.query('select diesel_device_submit($1,$2::jsonb) result',[token,JSON.stringify(payload)])).rows[0].result;
assert.equal((await submit(lease.token,bg)).id,bg.id);assert.equal((await submit(lease.token,bg)).duplicate,true);assert.equal((await submit('invalid',bg)).status,403);assert.equal((await db.query('select auth.uid() id')).rows[0].id,null);
await who(user,'admin@example.com');const records=(await db.query('select diesel_records() result')).rows[0].result.records;assert.equal(records.find(x=>x.id===bg.id).user_id,other);assert.equal(records.find(x=>x.id===bg.id).signature,'OPERADOR');const ops=await rpc('diesel_operations_admin',null);assert.equal(ops.operations.length,2);assert.equal(ops.locations[0].last_meter,1110);
await db.exec('reset role');await db.exec("delete from members where email='worker@example.com'");await who(null,null,'anon');assert.equal((await submit(lease.token,{...bg,id:crypto.randomUUID()})).status,403);
await who(user,'admin@example.com');await db.exec('reset role');await db.exec("update fleets set gmais_readings='{\"engine\":500}' where id='1001'");await who(user,'admin@example.com');assert.equal((await db.query('select diesel_session() result')).rows[0].result.fleets[0].last_engine,500);assert.equal((await rpc('diesel_operation_submit',{...r,id:crypto.randomUUID(),mode:'manual',liters:50,engine:499})).status,422);assert.equal((await rpc('diesel_operation_submit',{...r,id:crypto.randomUUID(),mode:'manual',liters:50,engine:500})).id!==undefined,true);await db.close();console.log('Operações, registradora, cache e envio em segundo plano: testes aprovados.');
