import catalog from '../../../lib/fleet-catalog.json';
import { env } from 'cloudflare:workers';
import { access,rules,json } from '../../../lib/access';
export async function GET(){const u=await access();if(u?.role!=='admin')return json({error:'Acesso restrito ao gestor.'},403);const members=await env.DB!.prepare('SELECT email,role,name FROM members ORDER BY name').all();return json({members:members.results,rules:await rules()});}
export async function POST(request: Request){const u=await access();if(u?.role!=='admin')return json({error:'Acesso restrito ao gestor.'},403);let b: any;try{b=await request.json()}catch{return json({error:'Dados inválidos.'},400)}
 if(!b||typeof b!=='object'||Array.isArray(b))return json({error:'Dados inválidos.'},400);
 if(b.action==='import-fleets'){for(let offset=0;offset<catalog.length;offset+=80){await env.DB!.batch(catalog.slice(offset,offset+80).map(f=>env.DB!.prepare('INSERT INTO fleets(id,name,type) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,type=excluded.type').bind(f.id,f.name,f.type)));}return json({ok:true,count:catalog.length});}
 else if(b.action==='fleet'){if(!/^[\w.-]{1,30}$/.test(b.id||'')||typeof b.name!=='string'||b.name.length<2||b.name.length>80||!['Trator','Colhedora','Caminhão','Outro'].includes(b.type))return json({error:'Informe código, nome e tipo válidos.'},422);await env.DB!.prepare('INSERT INTO fleets(id,name,type) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,type=excluded.type').bind(b.id.toUpperCase(),b.name,b.type).run();}
 else if(b.action==='member'){if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(b.email||'')||typeof b.name!=='string'||b.name.length<2||b.name.length>120||!['operator','admin'].includes(b.role))return json({error:'Informe nome, e-mail e perfil válidos.'},422);if(b.email.toLowerCase()===u.email.toLowerCase())return json({error:'Você não pode alterar seu próprio perfil.'},422);await env.DB!.prepare('INSERT INTO members(email,name,role) VALUES(?,?,?) ON CONFLICT(email) DO UPDATE SET name=excluded.name,role=excluded.role').bind(b.email.toLowerCase(),b.name,b.role).run();}
 else if(b.action==='rules'){if(!b.rules||['matchMeter','futureDate'].some(k=>typeof b.rules[k]!=='boolean'))return json({error:'Regras inválidas.'},422);await env.DB!.prepare("INSERT INTO settings(id,value) VALUES('rules',?) ON CONFLICT(id) DO UPDATE SET value=excluded.value").bind(JSON.stringify({matchMeter:b.rules.matchMeter,futureDate:b.rules.futureDate})).run();}
 else return json({error:'Ação inválida.'},400);return json({ok:true});}
