package br.com.abencoada.diesel;
import com.getcapacitor.*;
import com.getcapacitor.annotation.CapacitorPlugin;
import androidx.work.*;
import java.util.concurrent.TimeUnit;
import org.json.*;
@CapacitorPlugin(name="OfflineSync")
public class OfflineSyncPlugin extends Plugin {
 @PluginMethod public void configure(PluginCall call){try{synchronized(OfflineStore.LOCK){JSONObject state=OfflineStore.read(getContext());String user=call.getString("userId");if(!user.equals(state.optString("userId"))&&state.optJSONArray("queue")!=null&&state.getJSONArray("queue").length()>0){call.reject("Há registros pendentes de outra conta.");return;}state.put("userId",user);state.put("token",call.getString("token"));state.put("url",call.getString("url"));state.put("apikey",call.getString("apikey"));OfflineStore.write(getContext(),state);}schedule();call.resolve();}catch(Exception e){call.reject("Não foi possível preparar o envio automático.");}}
 @PluginMethod public void mirror(PluginCall call){try{synchronized(OfflineStore.LOCK){JSONObject state=OfflineStore.read(getContext());String user=call.getString("userId");if(!user.equals(state.optString("userId"))){call.resolve(new JSObject().put("ready",false));return;}JSONArray incoming=call.getArray("queue"),acks=state.optJSONArray("acks");if(acks==null)acks=new JSONArray();JSONArray pending=new JSONArray();for(int i=0;i<incoming.length();i++){JSONObject r=incoming.getJSONObject(i);boolean sent=false;for(int j=0;j<acks.length();j++)if(acks.getJSONObject(j).getString("id").equals(r.getString("id"))){sent=true;break;}if(!sent)pending.put(r);}state.put("queue",pending);OfflineStore.write(getContext(),state);call.resolve(new JSObject().put("ready",true).put("acks",acks).put("errors",state.optJSONArray("errors")==null?new JSONArray():state.getJSONArray("errors")));}schedule();}catch(Exception e){call.reject("Não foi possível guardar a fila de envio automático.");}}
 @PluginMethod public void acknowledge(PluginCall call){try{synchronized(OfflineStore.LOCK){JSONObject state=OfflineStore.read(getContext());if(!call.getString("userId").equals(state.optString("userId"))){call.resolve();return;}JSONArray ids=call.getArray("ids"),acks=state.optJSONArray("acks"),remaining=new JSONArray();if(acks!=null)for(int i=0;i<acks.length();i++){boolean remove=false;for(int j=0;j<ids.length();j++)if(ids.getString(j).equals(acks.getJSONObject(i).getString("id")))remove=true;if(!remove)remaining.put(acks.getJSONObject(i));}state.put("acks",remaining);OfflineStore.write(getContext(),state);}call.resolve();}catch(Exception e){call.reject("Não foi possível confirmar a fila.");}}
 private void schedule(){Constraints constraints=new Constraints.Builder().setRequiredNetworkType(NetworkType.CONNECTED).build();WorkManager manager=WorkManager.getInstance(getContext());manager.enqueueUniqueWork("abastece-sync-now",ExistingWorkPolicy.KEEP,new OneTimeWorkRequest.Builder(OfflineSyncWorker.class).setConstraints(constraints).setBackoffCriteria(BackoffPolicy.EXPONENTIAL,30,TimeUnit.SECONDS).build());manager.enqueueUniquePeriodicWork("abastece-sync-periodic",ExistingPeriodicWorkPolicy.KEEP,new PeriodicWorkRequest.Builder(OfflineSyncWorker.class,15,TimeUnit.MINUTES).setConstraints(constraints).build());}
}
